// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNusBKPyrIXzPOAWrO3Z25-jHq0YfzYqs',
    appId: '1:855670552236:web:83b9307fc6b72aa1ba1109',
    messagingSenderId: '855670552236',
    projectId: 'metfolio-e73cc',
    authDomain: 'metfolio-e73cc.firebaseapp.com',
    storageBucket: 'metfolio-e73cc.appspot.com',
    measurementId: 'G-V87K8DGHGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCrFdc3n6xDtmXdIdRtDF1epHTHRZRhng',
    appId: '1:855670552236:android:1023c8c1857164b1ba1109',
    messagingSenderId: '855670552236',
    projectId: 'metfolio-e73cc',
    storageBucket: 'metfolio-e73cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgO2TCZXEVN-uAEPVB3CZd6U5gsO2tJ80',
    appId: '1:855670552236:ios:b263ab6dbb89b581ba1109',
    messagingSenderId: '855670552236',
    projectId: 'metfolio-e73cc',
    storageBucket: 'metfolio-e73cc.appspot.com',
    androidClientId: '855670552236-765nnqnaierqnipb62f4l7s40k8ghgqt.apps.googleusercontent.com',
    iosClientId: '855670552236-579713ke3es8uej6d3t714enkpco4nlt.apps.googleusercontent.com',
    iosBundleId: 'com.metfolio.app',
  );
}
